name: "Jenkins caller action"
description: "Runs dockerised jenkins caller utility to be able to access Jenkins"
inputs:
  caCert:
    description: MTLS cacert
    required: true
  clientCert:
    description: MTLS client cert
    required: true
  clientKey:
    description: MTLS client key
    required: true
  jenkinsToken:
    description: Token to access jenkins job
    required: true
  jenkinsURL:
    description: URL of the Jenkins server
    required: true
  jenkinsUser:
    description: User to access Jenkins server
    required: true
  jenkinsPassword:
    description: Password to access Jenkins server
    required: true
  jenkinsJob:
    description: Name of the jenkins job
    required: true
  jenkinsJobOptions:
    description: "Options of the jenkins job. ex: key1=val1,key2=val2"
    required: true
runs:
  using: "composite"
  steps:
    - id: run-docker-action
      shell: bash
      run: |
        userName=$(git log -1 --format="%aN" $version)
        docker run --rm \
        --env CACERT="${{ inputs.caCert }}" \
        --env CERT="${{ inputs.clientCert }}" \
        --env KEY="${{ inputs.clientKey }}" \
        eu.gcr.io/tradeshift-public/jenkins-caller:master \
        --cert=/etc/jenkins-caller/client.cert \
        --key=/etc/jenkins-caller/client.key \
        --cacert=/etc/jenkins-caller/ca.crt \
        --token="${{ inputs.jenkinsToken }}" \
        --url="${{ inputs.jenkinsURL }}" \
        --user="${{ inputs.jenkinsUser }}" \
        --password="${{ inputs.jenkinsPassword }}" \
        --job="${{ inputs.jenkinsJob }}" \
        --options "${{ inputs.jenkinsJobOptions }}"
